language: node_js
before_install: npm install -g spark-cli
install:
- ./ci/create_spark_cli_json.sh
script:
- ./ci/run_memory_available_tests.sh
- ./ci/post_metric_to_librato.sh
env:
  global:
  - secure: eihq5J+oGVVWxZ2gsIAR8VPNUmfMqt5iPzbFMdUqZ80dHsdPr0WJhrPtITPJ1oN/Av2Qi6NVzblVZdfIphEclzkSTPN4fk7ve8WS0LIp8ali0fIp3+JffRz6BQQ+Mgx4a5pWZSqvKoiz7xtJ0gVnvYgcCWTsQQ/DzpObKpxhQZA=
  - secure: C1Iv+52IMV1fdlP8/jaBj14MSgGcVIb1PgnYsfSPR3x+cHHKD5MDcLUiqMQOlWeRoAs+xnpFe5fuS3yxUOFTFpZZ1SeZCyv4/1kMeBfYszRWPcJrb9/I0YNpI57Dywem7HzQD8Um9CIqMTyewttxPrvR2b28f/ZnPZ50sLcVR+w=
  - secure: Qq5I5heH7I/D4jxgeaxlEEbGfzbuNpRqGwHDcBIEabPKsp/zGDFvjNcPgr9hJvQ28AYCHYolv0brAqHgmHnD0UoU0+VPf7MGEW45BhL672Bb/0Csh8nJgDaNgtHA51ZtNn13+nKnj6cr23napnI2KbKJZtnVZIZfdoHD3hrqcjY=
  - secure: MInQpSy6aRRc9ixNXbG/ct6dEEfK3e5xR2LPJYDhyGDHoKKIxfBX7Wwsd44yhyZ8fNjXy1cR9hXjzhAkEzQV5zOmMBZTA2e1zk9KsZoqQB95L3doSnsh+n4aiOVo2pvFoTkGBz/WYwTv4prD3/NfXRrDVaRIrXY5BrqNNBmsZWM=
